### ISSUE TITLE
洛伦兹方程程序不全

### ISSUE THREAD

**Issue by M991131956** [nyasyamorina/trash-bin#1]
import os, numpy as np, matplotlib.pyplot as plt, cv2
import wave, struct, moviepy.editor as mpy
from mpl_toolkits.mplot3d import Axes3D

下列两行代码不全，应该如何补全？
**audio_data = # audio data, see `get_audio`.
picture_0_data =** 

class Lorentz_system:
    def __init__(self, R=28, sig=10, beta=8/3):
        self.cons = [R, sig, beta]
        self.point = list()
    def equation(self, p):
        R, sig, beta = self.cons
        x, y, z = p
        return np.array((sig*(y-x), x*(R-z)-y, x*y-beta*z))
    def rk4(self, p, dt):
        k1 = self.equation(p)
        k2 = self.equation(p + k1*dt/2)
        k3 = self.equation(p + k2*dt/2)
        k4 = self.equation(p + k3*dt)
        return (k1 + 2*k2 + 2*k3 + k4) / 6
    def run(self, dt, total_time):
        p = self.point[-1]
        for _ in np.arange(0, total_time, dt):
            p = p + self.rk4(p, dt)*dt
            self.point.append(p)
    def get_coordinates(self): return np.array(self.point).transpose(1, 0)

**Comment by nyasyamorina** [comment]
这两行是用来生成我投稿的b站的视频的, 第一个是bgm, 第二个是视频前几帧的画面.

不重要的东西, 删了就行,  代码下面相对应的东西也一起删掉就可以.
这个代码也是远古时代的东西了, 修是不会修的了.
